version: '3'

services:

  runner:
    image: apiki/github-actions-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - GH_REPOSITORY=${GH_REPOSITORY}
      - GH_RUNNER_TOKEN=${GH_RUNNER_TOKEN}
      - GH_RUNNER_LABELS=${GH_RUNNER_LABELS} \
    restart: unless-stopped